### PR TITLE
Update to new NanoGUI version

### PR DESCRIPTION
**Pull request by dvicini**
This pull request updates Nori to use the latest version of NanoGUI.

### CODE REVIEW

**Comment by wjakob** [comment]
It looks reasonable to me -- is it ready to be merged?

**Comment by wjakob** [comment]
Related: do the Python bindings still compile?

**Comment by dvicini** [comment]
We will test it on MacOS and Windows first to be sure, otherwise I think it should be ready. 

Which Python bindings do you mean?

**Comment by wjakob** [comment]
Oops, never mind about the bindings (context switch failure :-)).

**Pull request merged**
